// Copyright (c) Bodoconsult EDV-Dienstleistungen GmbH. All rights reserved.

// <auto-generated />

using EfConsoleApp1.Model.DatabaseModel.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EfConsoleApp1.Model.DatabaseModel.Migrations
{
    [DbContext(typeof(SqlServerExampleDbContext))]
    [Migration("20250401171019_V1_00")]
    partial class V1_00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfConsoleApp1.Model.DatabaseModel.Entities.AppSettings", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Key")
                    .IsRequired()
                    .HasMaxLength(255);

                b.Property<string>("Value");

                b.HasKey("ID");

                b.HasIndex("Key")
                    .IsUnique()
                    .HasName("AppSettingsKeyUnique");

                b.ToTable("AppSettings");
            });
            
            modelBuilder.Entity("EfConsoleApp1.Model.DatabaseModel.Entities.Users", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Rights")
                    .HasMaxLength(10);

                b.Property<string>("Password")
                    .HasMaxLength(15);

                b.Property<string>("Realname")
                    .HasMaxLength(40);

                b.Property<string>("Username")
                    .HasMaxLength(30)
                    .IsRequired();

                b.Property<string>("UserType")
                    .HasMaxLength(30);

                b.HasKey("ID");

                b.ToTable("TUsers");
            });

#pragma warning restore 612, 618
        }
    }
}
